version: '3.9'

services:
  postgresql:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}