version: '3.9'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - './postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres

